version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/2023-02-CECD2-4/frontend
    overwrite: yes
permissions:
  - object: /home/ec2-user/2023-02-CECD2-4/frontend
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: ec2-user