version: '3'
services:
  backend:
    ports:
      - 8080:8080
    depends_on:
      - my-redis # redis 동작해야 의미 O
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    env_file:
      - "./server/.env"
    volumes:
      - /home/app/node_modules
      - ./server:/home/app
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
  my-redis:
    image: redis:alpine