FROM node:alpine

# 작업 폴더 생성
WORKDIR /usr/src/app

# 설정 파일들 복사
COPY package*.json .

# 의존성 설치
RUN npm ci
# 나머지 파일들 복사
COPY . .
# 파일 빌드
# port 8080으로 외부 데이터 들을 수 있음
EXPOSE 8080

# 실행 시 보여줄 명령
CMD ["npm", "run", "start:dev"]
# ENTRYPOINT ["tail", "-f", "/dev/null"]